# Generated by Django 4.1.1 on 2022-10-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Total_Amount', models.FloatField()),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Profile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('Drug_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Drug_Name', models.CharField(max_length=100)),
                ('Drug_Details', models.CharField(max_length=200)),
                ('Drug_Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Phone_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Order_Amount', models.FloatField()),
                ('Order_Profile', models.CharField(max_length=200)),
                ('Bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.bill')),
                ('Drug_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Book',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Drug_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('Sell_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Drug_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('Storage_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Storage_Amount', models.IntegerField()),
                ('Drug_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.drugs')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('User_Password', models.CharField(max_length=100)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_First_Name', models.CharField(max_length=50)),
                ('User_Last_Name', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('User_Phone_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin_accounts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='admin_reviews',
            name='Book_id',
        ),
        migrations.RemoveField(
            model_name='admin_reviews',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='Book_ID',
        ),
        migrations.RemoveField(
            model_name='cart_item',
            name='Cart_ID',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='Book_id',
        ),
        migrations.RemoveField(
            model_name='delete',
            name='Book_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='Book_id',
        ),
        migrations.DeleteModel(
            name='edit_profile',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_review',
            name='Book_ID',
        ),
        migrations.RemoveField(
            model_name='user_review',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='admin_accounts',
        ),
        migrations.DeleteModel(
            name='admin_reviews',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cart_item',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='delete',
        ),
        migrations.DeleteModel(
            name='discount',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='publish',
        ),
        migrations.DeleteModel(
            name='user_review',
        ),
        migrations.AddField(
            model_name='pre_book',
            name='User_Phone_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacy.user_profile'),
        ),
    ]
