# Generated by Django 4.1.1 on 2022-12-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0003_delete_user_remove_sell_amount_alter_bill_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePanel',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
