# Generated by Django 4.1.1 on 2022-12-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0006_remove_employeepanel_id_alter_employeepanel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('drug_group', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employeepanel',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeepanel',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
